version: '3.8'

services:
  vllm:
    image: vllm/vllm-openai:latest
    ports:
      - "9000:9000"
    command: [
      "serve",
      "RedHatAI/gemma-3-27b-it-FP8-dynamic",
      "--served-model-name", "gemma3",
      "--host", "0.0.0.0",
      "--port", "9000",
      "--gpu-memory-utilization", "0.9",
      "--tensor-parallel-size", "1",
      "--max-model-len", "98304",
      "--disable-log-requests",
      "--dtype", "bfloat16",
      "--enable-chunked-prefill",
      "--enable-prefix-caching",
      "--max-num-batched-tokens", "8192",
      "--chat-template-content-format", "openai"
    ]
    # Add GPU support if needed
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: Dockerfile.server  # Assumes the second Dockerfile snippet is saved as Dockerfile.server
    ports:
      - "18889:18889"
    environment:
      - DWANI_API_BASE_URL=vllm  # Points to the vllm service for model inference on port 9000
    depends_on:
      - vllm
    volumes:
      - ./data:/data  # For session storage, adjust path as needed
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: Dockerfile.client  # Assumes the first Dockerfile snippet is saved as Dockerfile.client
    ports:
      - "8000:8000"  # Maps the Gradio app's default port 8000
    environment:
      - DWANI_API_BASE_URL=server  # Points to the server service on port 18889
    depends_on:
      - server
    restart: unless-stopped