services:
  vllm:
    image: vllm/vllm-openai:latest
    ports:
      - "9000:9000"
    command: [
      "--model", "RedHatAI/gemma-3-12b-it-FP8-dynamic",
      "--served-model-name", "gemma3",
      "--host", "0.0.0.0",
      "--port", "9000",
      "--gpu-memory-utilization", "0.9",
      "--tensor-parallel-size", "1",
      "--max-model-len", "8192",
      "--disable-log-requests",
      "--dtype", "bfloat16",
      "--enable-chunked-prefill",
      "--enable-prefix-caching",
      "--max-num-batched-tokens", "8192",
      "--chat-template-content-format", "openai"
    ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: server.Dockerfile  
    ports:
      - "8000:18889"
    environment:
      - DWANI_API_BASE_URL=vllm  
    depends_on:
      - vllm
    volumes:
      - ./data:/data  
    restart: unless-stopped

  tax_ui:
    build: ./dashboard/tax_ui
    ports:
      - "80:3000"
    depends_on:
      - server
    environment:
      - VITE_SANJEEVINI_BACKEND_APP_API_URL=http://0.0.0.0:8000/
  client:
    build:
      context: .
      dockerfile: client.Dockerfile  
    ports:
      - "8080:8000" 
    environment:
      - DWANI_API_BASE_URL=server  
    depends_on:
      - server
    restart: unless-stopped